### PR TITLE
created a new notebook and imnplemented the pipelines and GridSearch to…

### LINKED ISSUE #7: GridSearch didn't improve the model
@Donshenal @uta-dsc in order for us to follow up the case of my last pull request and mostly for us to practice more Git, I created this issue. Later on, whoever likes to resolve the issue, can create a new pull request and link it to this issue. I'll try to work on it today.

### PR DESCRIPTION
**Pull request by mojtaba-peyrovi**
@Donshenal @uta-dsc, I added a new notebook with the pipeline implementation for the diabetes analysis. It all went well but at the end when I used the best model chosen by GridSearch, despite it showing 78% of accuracy when I call **grid_logreg.best_score_** , at the end when I use ``` best_model = grid_logreg.best_estimator_ ``` and evaluate it again, it shows 74% of accuracy. I haven't found the reason why but maybe we you guys can find an answer for it?

image

### CODE REVIEW

**Review by Donshenal — APPROVED** [review]

**Comment by Donshenal** [comment]
Thanks for the work! 
Ok that sounds strange, will have a look. 
Also, why is the recall much worse than the log reg predictions without optimization? 
In this case the recall would be an important value, right?

**Comment by Donshenal** [comment]
Alright I figured it out :)

grid_logreg = GridSearchCV(
    l_regression_pipe,
    param_grid=param_logreg,
    scoring="accuracy",
    cv=5
)

Here you did set the score as the accuracy, but GridSearch uses cross-validation for determining the best score 
(that's why its called GridSearchCV), so the 'best score' value in your notebook is the average cross validation accuracy for 5 different sub train-test splits with the traindata  (which you set by cv=5) and the final evaluation accuracy in the end is the accuracy for the (new) testdata.

Still pretty strange that it performs significanlyt worse than the log reg model without any GridSearchCV optimisation.

**Comment by mojtaba-peyrovi** [comment]
Thank you Don. I did a quick and dirty work since I was distracted by my kids, but I thought we can take it from there and improve it. I tried to follow the previous exercise we did live with Carmine on Friday using pipeline, but there is a chance I made a mistake somewhere. Also, what I found very interesting yet confusing is there are several hyper parameters that we can play with and a slight change in one of them can make a big difference in the final results. In this case I don't really know what should be the strategy to fine tune the model because it's impossible to check hundreds of different combinations of parameters. Maybe it is the reason we better use RandomGridSearch. I'll try to use it today (if I get any free time from kids) and check if there will be any further improvement. Have a nice Sunday!

**Comment by Donshenal** [comment]
No you did everything correctly, the code looks good and I'm impressed you implemented a pipeline so quickly.

Now thinking about it a bit more the result does make sense, by setting the scoring to accuracy it only evaluates on accuracy, which is then with 0.78 indeed higher than the testset accuracy of 0.76 before with the unoptimized model. Unfortunately this small increase comes with the downside of a sharp decrease in recall, which is just a coincidence and GridSearchCV doesn't care, because you only told it to look at the overall accuracy.  

In this case it would make sense to focus more on recall, so I changed the scoring in your code to 'recall' and ran it again and then the model has a recall of 1.0 both for traindata and the new testdata :)  This comes of course with a sharp decline of precision (only 0.35), so is has many false positives but then the model is perfect at detecting everyone with diabetes, is just overdetects, but I think this would be the preferred option here.

**Comment by Donshenal** [comment]
Capture_1

Capture_2


Capture_3

**Comment by mojtaba-peyrovi** [comment]
It makes sense. Thank you for checking.

**Comment by Donshenal** [comment]
You're welcome, have a nice Sunday and see you tomorrow :)

**Comment by mojtaba-peyrovi** [comment]
Thanks, likewise!

**Pull request merged**
